name: Update VN IP List
on:
  schedule:
    - cron: '0 0 * * *' # Chạy tự động vào 0h mỗi ngày
  workflow_dispatch: # Cho phép bạn bấm nút chạy thủ công

jobs:
  update-ip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get VN IP from APNIC
        run: |
          curl -s http://ftp.apnic.net/stats/apnic/delegated-apnic-latest | grep "apnic|VN|ipv4|" | awk -F'|' '{printf "%s/%d\n", $4, 32-log($5)/log(2)}' > vn-ip.txt

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add vn-ip.txt
          git commit -m "Update VN IP list" || exit 0
          git push
