name: Update VN Resources
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-list:
    runs-on: ubuntu-latest
    env: # Thêm dòng này để hết cảnh báo vàng
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Process IP and Domains
        run: |
          # 1. Lấy IP từ APNIC
          curl -s http://ftp.apnic.net/stats/apnic/delegated-apnic-latest | grep "apnic|VN|ipv4|" | awk -F'|' '{printf "%s/%d\n", $4, 32-log($5)/log(2)}' > final-list.txt
          
          # 2. Thêm Domain từ file cá nhân (nếu file tồn tại)
          if [ -f "my-domains.txt" ]; then
            echo "" >> final-list.txt
            cat my-domains.txt >> final-list.txt
          fi

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add final-list.txt
          git commit -m "Update VN IP and Domain list" || exit 0
          git push
